[target.aarch64-linux-android]
linker = "/opt/homebrew/share/android-ndk/toolchains/llvm/prebuilt/darwin-aarch64/bin/aarch64-linux-android26-clang"
ar = "/opt/homebrew/share/android-ndk/toolchains/llvm/prebuilt/darwin-aarch64/bin/llvm-ar"
